version: '3.9'

services:

 
  db:
    image: postgres
    restart: always
    ports:
      - 5644:5432
    environment:
      POSTGRES_PASSWORD: user11920
      POSTGRES_USER: user
      POSTGRES_DB: UserDB



 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080